name: Nitesh Kumar

  avatar: "https://github.com/nkcool5/nkcool5.github.io/blob/master/images/32159737.jpeg"

footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: true
  youtube: false
  spotify: false
  telephone: false
  steam: false
  twitch: false
  yelp: false
  
  share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
