# Site wide configuration

title: Site Title
locale: en_US
description: Describe your website here.
logo: 32159737.jpeg
search: true

# Site owner
owner:
  name: Your Name
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

