# Site settings
name: Nitesh Kumar
title: Cyber-Security
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
header-img: "/images/IMG_20171026_153523.jpg"
footer-links-active:
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: true
footer-links:
linkedin: https://www.linkedin.com/in/nitesh-kumar-405415a2/
twitter: https://twitter.com/niteshkumar1896
theme: jekyll-theme-midnight
